package models

const (
	codeTemplate = `// DON'T EDIT *** generated by go-db-models *** DON'T EDIT //
package {{.PackageName}}

//import "database/sql"

// 对应数据表：{{.Name}}
type {{.Name|Format2StructName}}Table struct {
	{{range _, $v := .Fields}}
	{{$v.Name|Format2StructName}}  {{$v.Type}}
	{{end}}
}
`
)
