package models

const (
	codeTemplate = `// DON'T EDIT *** generated by go-db-models *** DON'T EDIT //
package {{.PackageName}}

{{range $k, $v := .Imports}}
import "{{$v}}"{{end}}

// 对应数据表：{{.Name}}
type {{.Name|Format2StructName}}Table struct { 
{{range $k, $v := .Fields}}
{{$v.Name|Format2StructName}}  {{$v.Type}} ` + "`name:\"{{$v.Name}}\"`" + `{{end}}
}
`
)
