package models

const (
	// 生成的数据表的文件的模版: gen_table_*.go
	testCodeTemplate = `// DON'T EDIT *** generated by go-db-models *** DON'T EDIT //

package {{.PackageName}}

import (
	"database/sql"
	"fmt"
	"testing"
)

func Test{{.Name|Format2StructName}}QueryRowWhere(t *testing.T) {
	db := testGetDb()
	_, err := {{.Name|Format2StructName}}QueryRowWhere(db, "1")
	if err == sql.ErrNoRows {
		fmt.Println(err.Error() + " in QueryRowWhere of {{.Name}}")
	} else if err != nil {
		t.Fatal(err)
	}
}

func Test{{.Name|Format2StructName}}QueryWhere(t *testing.T) {
	db := testGetDb()
	_, err := {{.Name|Format2StructName}}QueryWhere(db, "1")
	if err == sql.ErrNoRows {
		fmt.Println(err.Error() + " in QueryWhere of {{.Name}}")
	} else if err != nil {
		t.Fatal(err)
	}
}
`
)
